### PR TITLE
A few tidbits to get this to work on Android

### PR DESCRIPTION
**Pull request by xyzz**
* base64: char is unsigned on ARM, need to explicitly mark it as signed because the code uses -1
* getGLVersionNumber: cache return value from glGetString, calling it multiple times crashes

### CODE REVIEW

**Comment by xyzz** [comment]
Updated to use upstream base64 fix instead of my own fix.

**Comment by psi29a** [comment]
@scrawl what do you think?

**Comment by psi29a** [comment]
Do you believe this is something that should go upstream?

**Comment by sandstranger** [comment]
Without it you even can not build osg for Android  on ndk ) , because Android - shit

**Comment by xyzz** [comment]
Updated yet again to support `OSG_GL1_AVAILABLE` on android with the gl4es wrapper.

**Comment by xyzz** [comment]
Are there still any problems with this pull request?

Edit: I could remove the `static char *versionstring` thing if you don't like it - shouldn't matter on gl4es.

**Comment by ghost** [comment]
> I could remove the static char *versionstring thing if you don't like it - shouldn't matter on gl4es.

Yes please.

> Are there still any problems with this pull request?

The plan with our fork is to stay as close to upstream as possible. Have you considered proposing the libGL.so change to them? I'm slightly afraid it may be rejected for the reason that wrappers are not an intended use, but then again it's not like having proper GL on Android is something that could never happen.

**Comment by xyzz** [comment]
In fact, nvidia hardware has desktop GL support on android: http://jamesdolan.blogspot.fr/2014/06/opengl-44-and-beyond-on-android.html

Edit: but it seems they don't have libGL.so, not sure how exactly it works :/

**Comment by xyzz** [comment]
https://github.com/openscenegraph/OpenSceneGraph/pull/463

**Comment by xyzz** [comment]
upstream has merged it now

**Pull request merged**
